apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-pv
  namespace: weather-monitoring
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/weather
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-pvc
  namespace: weather-monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
